ACCOUNT_ID: 701393882251
AWS_REGION: us-east-1
REST_API_ID: z4rww46vh0
REST_API_ROOT_RESOURCE_ID: cey6nsjaqg
SENTRY_DNS: 'https://66115b5faef941bb9078104b8ef3b222@sentry.ec.pe/84'
ENDPOINT_DB: 
USER: innovador
PASSWORD: 
HOST: 
PORT: 5432
DATABASE: db_innovacion
SCHEMA: public
SNET1: subnet-05cfd39d3c64434e6
SNET2: subnet-07681388ed0f5d675
SG: sg-02988575e7a3a8c25
MAIL_RELAY: 52.55.145.190
BUCKET: dev.topcis.emblue
ENDPOINT_EMBLUE: 'https://track.embluemail.com/contacts/event'
ENDPOINT_EMBLUE_BULK: 'https://track.embluemail.com/contacts/event/bulk'
EMBLUE_FTP_HOST: app.embluemail.com
GESTION_NEWSLETTER_CODE: gestion_newsletter
GESTION_NEWSLETTER_API_KEY: 
GESTION_NEWSLETTER_ID: 12154
GESTION_NEWSLETTER_FTP_PASS: 
GESTION_CAMPAIGN_CODE: gestion_campaign
GESTION_CAMPAIGN_API_KEY: 
GESTION_CAMPAIGN_ID: 15273
GESTION_CAMPAIGN_FTP_PASS: 
COMERCIO_NEWSLETTER_CODE: comercio_newsletter
COMERCIO_NEWSLETTER_API_KEY: 
ELCOMERCIO_NEWSLETTER_ID: 15274
ELCOMERCIO_NEWSLETTER_FTP_PASS: 
ELCOMERCIO_CAMPAIGN_ID: 15272
ELCOMERCIO_CAMPAIGN_FTP_PASS: 
ELCOMERCIO_CAMPAIGN_CODE: elcomercio_campaign
ELCOMERCIO_CAMPAIGN_API_KEY: 

SENDY_API: 'http://newsletter.peruid.pe/subscribe'
PERU21_CODE: 'peru21'
PERU21_LIST: ''
TROME_CODE: 'trome'
TROME_LIST: ''
DEPOR_CODE: 'depor'
DEPOR_LIST: ''
CORREO_CODE: 'correo'
CORREO_LIST: ''